### ISSUE TITLE
Release v. 0.5.0

### ISSUE THREAD

**Issue by dblock** [jenkinsci/ansicolor-plugin#99] opened 2017-03-17 00:42 UTC
This looks like a job for @Joe-Merten (repo invite in https://github.com/dblock/jenkins-ansicolor-plugin/invitations). I would bump the version to 0.5.0 since Jansi and major changes. Instructions [here](https://github.com/dblock/jenkins-ansicolor-plugin/blob/master/RELEASING.md).

**Comment by Joe-Merten** [comment] 2017-03-17 12:01
Hmm, reading: 

> You must have r/w permissions to github.com/dblock/jenkins-ansicolor-plugin under the same username.

But I'm `Joe-Merten` on github and `joe_merten` on https://accounts.jenkins.io (because the latter disallow hypen in username).

**Comment by dblock** [comment] 2017-03-17 12:03
I am not sure how to deal with that, it's possible that somewhere we have this assumption baked in, you can fix it ;)

**Comment by Joe-Merten** [comment] 2017-03-17 12:16
> Ensure that the version in pom.xml is correct and ends with `-SNAPSHOT`.

But for the release, the `-SNAPSHOT` postfix should be released, right (seeing this in your last commits)?

**Comment by dblock** [comment] 2017-03-17 13:01
AFAIK, maybe RELEASING needs an update re: that

**Comment by Joe-Merten** [comment] 2017-03-17 15:45
Might review the updated `RELEASING.md`?

**Comment by ssbarnea** [comment] 2017-03-17 21:07
No need to implement hacks, JANSI 1.15 was release so just update version, compile and release.

**Comment by dblock** [comment] 2017-03-17 22:44
@ssbarnea jenkins ships with its own version of Jansi so YMMV unless you have the latest jenkins, we have a ton of users having this problem

**Comment by dblock** [comment] 2017-03-17 22:45
@Joe-Merten LGTM

**Comment by ssbarnea** [comment] 2017-03-17 23:04
I do not see this as critical error, it would a good reason for them to keep their jenkins updated.

-- sorin

**Comment by JoeMerten** [comment] 2017-03-18 12:34
… just changed my github username from `Joe-Merten` to `JoeMerten` as recommeded by ssbarnea …

**Comment by JoeMerten** [comment] 2017-03-18 14:14
Tried to make release (my first time), but running into issues.

Following the instructions from [RELEASING.md](https://github.com/dblock/jenkins-ansicolor-plugin/blob/master/RELEASING.md), a.o. executing `mvn release:prepare release:perform`. After interactively answering the questions about release version, SCM release tag and new development version (finding out, that my [recent changes in RELEASING.md](https://github.com/dblock/jenkins-ansicolor-plugin/commit/ba27a745a7c066b70b70d97ac50c1aea3d204a1f) are completely wrong ;-), I got an error in the deployment stage:

    [INFO] [INFO] --- maven-deploy-plugin:2.6:deploy (default-deploy) @ ansicolor ---
    [INFO] Uploading: https://repo.jenkins-ci.org/releases/org/jenkins-ci/plugins/ansicolor/0.5.0/ansicolor-0.5.0.hpi
    [INFO] …
    [INFO] Uploading: https://repo.jenkins-ci.org/releases/org/jenkins-ci/plugins/ansicolor/0.5.0/ansicolor-0.5.0.pom
    [INFO] …
    [INFO] [INFO] ------------------------------------------------------------------------
    [INFO] [INFO] BUILD FAILURE
    [INFO] [INFO] ------------------------------------------------------------------------
    [INFO] [INFO] Total time: 36.622 s
    [INFO] [INFO] Finished at: 2017-03-18T14:18:23+01:00
    [INFO] [INFO] Final Memory: 80M/833M
    [INFO] [INFO] ------------------------------------------------------------------------
    [INFO] [ERROR] Failed to execute goal org.apache.maven.plugins:maven-deploy-plugin:2.6:deploy (default-deploy) on project ansicolor: Failed to deploy artifacts: Could not transfer artifact org.jenkins-ci.plugins:ansicolor:hpi:0.5.0 from/to repo.jenkins-ci.org (https://repo.jenkins-ci.org/releases/): Access denied to: https://repo.jenkins-ci.org/releases/org/jenkins-ci/plugins/ansicolor/0.5.0/ansicolor-0.5.0.hpi, ReasonPhrase: Forbidden. -> [Help 1]
    [INFO] [ERROR] 
    [INFO] [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
    [INFO] [ERROR] Re-run Maven using the -X switch to enable full debug logging.
    [INFO] [ERROR] 
    [INFO] [ERROR] For more information about the errors and possible solutions, please read the following articles:
    [INFO] [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
    [INFO] ------------------------------------------------------------------------
    [INFO] BUILD FAILURE
    [INFO] ------------------------------------------------------------------------
    [INFO] Total time: 02:26 min
    [INFO] Finished at: 2017-03-18T14:18:23+01:00
    [INFO] Final Memory: 18M/306M
    [INFO] ------------------------------------------------------------------------
    [ERROR] Failed to execute goal org.apache.maven.plugins:maven-release-plugin:2.5.1:perform (default-cli) on project ansicolor: Maven execution failed, exit code: '1' -> [Help 1]
    [ERROR] 
    [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
    [ERROR] Re-run Maven using the -X switch to enable full debug logging.
    [ERROR] 
    [ERROR] For more information about the errors and possible solutions, please read the following articles:
    [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
    
Full buildlog: [ansicolor-0.5.0-release-buildlog.txt](https://github.com/dblock/jenkins-ansicolor-plugin/files/852454/ansicolor-0.5.0-release-buildlog.txt); also checked https://repo.jenkins-ci.org/releases/org/jenkins-ci/plugins/ansicolor/, seeing that 0.5.0 has not been arrived.

Double checked my `~/.m2/settings.xml` but dont see the problem.

However, the `mvn release:prepare release:perform` has done 2 git commits:

- 87c0ce5ee0e11806000339cb341e05041e2d5c7e [maven-release-plugin] prepare release ansicolor-0.5.0
  - Releasetag has been created (https://github.com/dblock/jenkins-ansicolor-plugin/releases)
- 8c5bc359c52828a144d70b0548ba136a19897c2c  [maven-release-plugin] prepare for next development iteration
  - 0.5.0 → 0.5.1-SNAPSHOT

**Comment by dblock** [comment] 2017-03-18 14:26
Can you actually login to https://repo.jenkins-ci.org?

**Comment by dblock** [comment] 2017-03-18 14:28
You should rewind git with a `git reset --hard` probably back to the state where it was before and force push it, then attempt a re-release *after* checking that you can actually push to  https://repo.jenkins-ci.org/

**Comment by JoeMerten** [comment] 2017-03-18 15:12
Login to https://repo.jenkins-ci.org works (had created a new account with my changed username `JoeMerten`. https://repo.jenkins-ci.org acceppts both `JoeMerten` and `joemerten`.

**Comment by JoeMerten** [comment] 2017-03-18 15:19
Checking https://repo.jenkins-ci.org/webapp/#/home, then Set Me Up → releases, it shows me: "You do not have deploy permissions to this repository"

![no-permission](https://cloud.githubusercontent.com/assets/6552470/24073340/935c10ba-0bf6-11e7-9835-792f5c1942fe.png)

**Comment by JoeMerten** [comment] 2017-03-18 17:09
Checked the above mentioned screenshot against ansicolor [pom.xml](https://github.com/dblock/jenkins-ansicolor-plugin/blob/master/pom.xml):

```
  <distributionManagement>
    <repository>
      <id>repo.jenkins-ci.org</id>
      <url>https://repo.jenkins-ci.org/releases/</url>
    </repository>
  </distributionManagement>
```

differs in some points:

| Location | `<id>` | `<name>` | `<url>` |
|----------|----------|----------|----------|
| https://repo.jenkins-ci.org | `central` | `jenkinsci-releases` | `https://repo.jenkins-ci.org/releases` |
| ansicolor pom.xml | `repo.jenkins-ci.org` | | `https://repo.jenkins-ci.org/releases/` |







- `<id>repo.jenkins-ci.org</id>` versus <id>repo.jenkins-ci.org</id>

**Comment by dblock** [comment] 2017-03-18 19:21
@JoeMerten I am not sure how to fix this, every time we had someone do this it was yet another new process since they change everything - if you tell me what to do I'll grant you whatever permissions are required?

**Comment by JoeMerten** [comment] 2017-03-19 11:11
Unfortunately, I have completely now idea about the root cause for the permission issue.
I'd now contated jfrog support via email and will see if they can help.

**Comment by ssbarnea** [comment] 2017-03-19 11:14
If you need help I could try to help, my account name is the same on all systems (ssbarnea).

**Comment by dblock** [comment] 2017-03-19 13:21
@ssbarnea I can make a release, that's not the problem, I'd like @JoeMerten to be setup and running here end-to-end because he has contributed boat loads of code.

**Comment by dblock** [comment] 2017-03-19 13:31
I re-read https://wiki.jenkins-ci.org/display/JENKINS/Hosting+Plugins#HostingPlugins-Requestuploadpermissions, that has changed. Looks like we need to request r/w access for you now via a PR.

@JoeMerten make sure you've logged into https://repo.jenkins-ci.org/webapp/#/login once at least, it's apparently required.

I've done that here: https://github.com/jenkins-infra/repository-permissions-updater/pull/258

Will you please add the instructions ^ to RELEASING if that works?

**Comment by JoeMerten** [comment] 2017-03-19 16:44
I'll update `RELEASING.md` when I'd completed the release; even for the interactive versioning step during `mvn release:prepare`.
Regarding jenkins-infra/repository-permissions-updater#258: Seeing, that at jenkins / jfrog registering my `JoeMerten` has been impicitely converted to lowercase registered username `joemerten`. I'll see if it works however.

If permission issue has been solved, I need to find out how to perform upload retry via `mvn release:perform` (without reexecution of `mvn release:prepare`). Found some instructions [here](http://maven.apache.org/maven-release/maven-release-plugin/examples/perform-release.html) and [here](http://maven.apache.org/maven-release/maven-release-plugin/perform-mojo.html), but have not succeeded until now. Did you have experience about this?

Seems that

    mvn release:perform -DconnectionUrl=scm:git:git@github.com:dblock/jenkins-ansicolor-plugin.git -Dtag=ansicolor-0.5.0

is still buggee (see [SO](http://stackoverflow.com/questions/18943347/how-to-run-releaseperform-from-a-given-git-tag)) and I have to workaround it. I think I'll try it with:

    git checkout ansicolor-0.5.0 && mvn clean deploy

**Comment by dblock** [comment] 2017-03-19 16:54
I've done a release from a tag, but feel free to rewind `master` forcefully.

**Comment by dblock** [comment] 2017-03-19 19:19
@JoeMerten looks like https://github.com/jenkins-infra/repository-permissions-updater/pull/258 is resolved, party on.

**Comment by JoeMerten** [comment] 2017-03-19 22:29
`mvn deploy` has now succeeded and ansicolor-0.5.0 has been arrived at https://repo.jenkins-ci.org/releases/org/jenkins-ci/plugins/ansicolor :-)

**Comment by dblock** [comment] 2017-03-19 23:03
You should close this issue @JoeMerten if it's all done.

**Comment by JoeMerten** [comment] 2017-03-20 15:36
Yep, I'll close it it's all done. But for the definition of done, I also want to see 0.5.0 in production.
Checked yesterday in a fresh installed jenkins 1.653, still provides me 0.4.3. Checked now again, seeing the new 0.5.0:-)

Manage Jenkins → Manage Plugins → Available
→ AnsiColor is displayed with 0.5.0
But when clicking `AnsiColor` which is a link to https://plugins.jenkins.io/ansicolor, it displays old information:
<kbd>![ansicolor-wiki-screenshot](https://cloud.githubusercontent.com/assets/6552470/24101793/f0001fee-0d79-11e7-99be-555342ad3c42.png)</kbd>
Need to change this manually?!

Clicking on 
<kbd>![ansicolor-wiki-screenshot-edit](https://cloud.githubusercontent.com/assets/6552470/24102202/77276f3a-0d7b-11e7-94ca-1e11b87fcb33.png)</kbd>
directs me to https://wiki.jenkins-ci.org/display/JENKINS/AnsiColor+Plugin which shows correct 0.5.0
<kbd>![ansicolor-wiki-screenshot2](https://cloud.githubusercontent.com/assets/6552470/24102456/548e6162-0d7c-11e7-95bb-5c79d3d84d82.png)</kbd>

However, after installing the ansicolor plugin, it works as expected.

Also testet with a fresh installed jenkins 2.32.2 and 2.50 results in the same behaviour as with 1.653.

Hmm, seeing curios exceptions on jenkins console and not sure if I saw em before → #101.

**Comment by JoeMerten** [comment] 2017-03-20 18:42
Will close if the old version info display is solved, but have no idea.

**Comment by dblock** [comment] 2017-03-20 19:45
I *think* that just takes some time.

**Comment by JoeMerten** [comment] 2017-03-21 22:48
Created Jenkins Issue: https://issues.jenkins-ci.org/browse/JENKINS-43007

**Comment by JoeMerten** [comment] 2017-03-23 15:04
Seeing, that https://plugins.jenkins.io/ansicolor have been synced now:
<kbd>![screenshot_20170323_155926](https://cloud.githubusercontent.com/assets/6552470/24253947/f2b602a2-0fe1-11e7-9921-bd76a9357f26.png)</kbd>
They even have changed the style / layout minimal but also took the pipeline example snippets which I'd recently added to https://wiki.jenkins-ci.org/display/JENKINS/AnsiColor+Plugin.

See also https://github.com/jenkins-infra/jenkins-infra/pull/706

So I think it's done now.

@dblock: I'll now turn back to my payed work for a while. See you next time.

**Closed by JoeMerten** 2017-03-23 15:04 UTC
Labels: chore

**Comment by dblock** [comment] 2017-03-23 15:25
Thanks for all your help @JoeMerten! You were far and wide into the whole ANSI coloring ;)
